function(derammo_scan_library_sources DERAMMO_TARGET DERAMMO_LIBRARY_TYPE)
    message(STATUS "${DERAMMO_TARGET} looking for sources in ${CMAKE_CURRENT_SOURCE_DIR}")

    file(GLOB DERAMMO_PUBLIC_SOURCES
        LIST_DIRECTORIES false
        RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
        CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/*.c
        ${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/*.h
    )
    message(STATUS "${DERAMMO_TARGET} public sources: ${DERAMMO_PUBLIC_SOURCES}")
    set(DERAMMO_PUBLIC_SOURCES ${DERAMMO_PUBLIC_SOURCES} PARENT_SCOPE)

    file(GLOB_RECURSE DERAMMO_INTERFACE_SOURCES
        LIST_DIRECTORIES false
        RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
        CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_SOURCE_DIR}/include/*.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp
    )
    message(STATUS "${DERAMMO_TARGET} interface sources: ${DERAMMO_INTERFACE_SOURCES}")
    set(DERAMMO_INTERFACE_SOURCES ${DERAMMO_INTERFACE_SOURCES} PARENT_SCOPE)

    file(GLOB_RECURSE DERAMMO_PRIVATE_SOURCES
        LIST_DIRECTORIES false
        RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
        CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h
        ${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c
        ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
    )
    message(STATUS "${DERAMMO_TARGET} private sources: ${DERAMMO_PRIVATE_SOURCES}")
    set(DERAMMO_PRIVATE_SOURCES ${DERAMMO_PRIVATE_SOURCES} PARENT_SCOPE)

    file(GLOB_RECURSE DERAMMO_GTEST_SOURCES
        LIST_DIRECTORIES false
        RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
        CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_SOURCE_DIR}/gtest/*.h
        ${CMAKE_CURRENT_SOURCE_DIR}/gtest/*.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/gtest/*.c
        ${CMAKE_CURRENT_SOURCE_DIR}/gtest/*.cpp
    )
    message(STATUS "${DERAMMO_TARGET} gtest sources: ${DERAMMO_GTEST_SOURCES}")
    set(DERAMMO_GTEST_SOURCES ${DERAMMO_GTEST_SOURCES} PARENT_SCOPE)
endfunction()
