if(CMAKE_GENERATOR MATCHES "Unix")
	# we generate a separate build tree for each build type, so no need to include that in the paths
	set(DERAMMO_BUILD_OUTPUT_PATH	"${CMAKE_CURRENT_BINARY_DIR}")
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY	${DERAMMO_BUILD_OUTPUT_PATH}/bin)
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY	${DERAMMO_BUILD_OUTPUT_PATH}/lib)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY	${DERAMMO_BUILD_OUTPUT_PATH}/lib)
	set(DERAMMO_INSTALL_INIT_D "/etc/init.d")
	set(DERAMMO_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/")
elseif(CMAKE_GENERATOR MATCHES "Visual Studio")
	set(DERAMMO_BUILD_OUTPUT_PATH "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE}")
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG	${DERAMMO_BUILD_OUTPUT_PATH}/bin/Debug)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO	${DERAMMO_BUILD_OUTPUT_PATH}/bin/RelWithDebInfo)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE	${DERAMMO_BUILD_OUTPUT_PATH}/bin/Release)
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG	${DERAMMO_BUILD_OUTPUT_PATH}/bin/Debug)
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO	${DERAMMO_BUILD_OUTPUT_PATH}/bin/RelWithDebInfo)
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE	${DERAMMO_BUILD_OUTPUT_PATH}/bin/Release)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG	${DERAMMO_BUILD_OUTPUT_PATH}/bin/Debug)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO	${DERAMMO_BUILD_OUTPUT_PATH}/bin/RelWithDebInfo)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE	${DERAMMO_BUILD_OUTPUT_PATH}/bin/Release)
	set(DERAMMO_INSTALL_INIT_D init.d)
	set(DERAMMO_INSTALL_PREFIX "")
endif()

set(DERAMMO_INSTALL_BINDIR ${DERAMMO_INSTALL_PREFIX}bin)
set(DERAMMO_INSTALL_LIBDIR ${DERAMMO_INSTALL_PREFIX}lib)
set(DERAMMO_INSTALL_DOCDIR ${DERAMMO_INSTALL_PREFIX}doc)
set(DERAMMO_INSTALL_LOGDIR ${DERAMMO_INSTALL_PREFIX}log)
set(DERAMMO_INSTALL_TMPDIR ${DERAMMO_INSTALL_PREFIX}tmp)
set(DERAMMO_INSTALL_LICENSEDIR ${DERAMMO_INSTALL_DOCDIR}/licenses)

# reference this to make it no longer unused in some projects
set(DERAMMO_RELATIVE_BINARY_DIR ${DERAMMO_RELATIVE_BINARY_DIR})

# java build output relative path
set(DERAMMO_JAVABUILD_OUTPUT javabuild)

# runtime copy location, which is used as the cwd for test runs
# to be populated during build
set(DERAMMO_RUNTIME_DIR ${CMAKE_BINARY_DIR}/runtime)
